package com.example.core.constants

const val CORE = "core_jungmil"
const val TUTORIAL = "tutorial"
const val PASSWORD_REGEX = "^[a-zA-Z0-9]{6,}$"
const val USER_LIST = "회원목록"
const val LOADING = "loading"
const val OWNER_EMAIL = "...."
const val AUTO_LOGIN = "auto_login"
const val EMAIL = "email"
const val NAME = "name"
const val COMPANY = "company"
const val POSITION = "position"
const val CELL_PHONE = "cell_phone"
const val SELF = "구직"
const val CALL = "구인"
const val SUGGESTION = "건의사항"